EXTRAFLAGS += -flto
OLED_DRIVER_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
SPLIT_KEYBOARD = yes
DEBOUNCE_TYPE = sym_defer_g

UNICODE_ENABLE   = no # Unicode
MOUSEKEY_ENABLE  = no # Mouse keys(+4700)
